/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/_dashboard'
import { Route as DashboardIndexRouteImport } from './routes/_dashboard.index'
import { Route as DashboardSettingsRouteImport } from './routes/_dashboard.settings'
import { Route as DashboardRequestsRouteImport } from './routes/_dashboard.requests'
import { Route as DashboardPresenceRouteImport } from './routes/_dashboard.presence'
import { Route as DashboardEmployeesRouteImport } from './routes/_dashboard.employees'
import { Route as DashboardAlertsRouteImport } from './routes/_dashboard.alerts'

const DashboardRoute = DashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardRequestsRoute = DashboardRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPresenceRoute = DashboardPresenceRouteImport.update({
  id: '/presence',
  path: '/presence',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardEmployeesRoute = DashboardEmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAlertsRoute = DashboardAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof DashboardIndexRoute
  '/alerts': typeof DashboardAlertsRoute
  '/employees': typeof DashboardEmployeesRoute
  '/presence': typeof DashboardPresenceRoute
  '/requests': typeof DashboardRequestsRoute
  '/settings': typeof DashboardSettingsRoute
}
export interface FileRoutesByTo {
  '/alerts': typeof DashboardAlertsRoute
  '/employees': typeof DashboardEmployeesRoute
  '/presence': typeof DashboardPresenceRoute
  '/requests': typeof DashboardRequestsRoute
  '/settings': typeof DashboardSettingsRoute
  '/': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_dashboard': typeof DashboardRouteWithChildren
  '/_dashboard/alerts': typeof DashboardAlertsRoute
  '/_dashboard/employees': typeof DashboardEmployeesRoute
  '/_dashboard/presence': typeof DashboardPresenceRoute
  '/_dashboard/requests': typeof DashboardRequestsRoute
  '/_dashboard/settings': typeof DashboardSettingsRoute
  '/_dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alerts'
    | '/employees'
    | '/presence'
    | '/requests'
    | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to: '/alerts' | '/employees' | '/presence' | '/requests' | '/settings' | '/'
  id:
    | '__root__'
    | '/_dashboard'
    | '/_dashboard/alerts'
    | '/_dashboard/employees'
    | '/_dashboard/presence'
    | '/_dashboard/requests'
    | '/_dashboard/settings'
    | '/_dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DashboardRoute: typeof DashboardRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/': {
      id: '/_dashboard/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/settings': {
      id: '/_dashboard/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/requests': {
      id: '/_dashboard/requests'
      path: '/requests'
      fullPath: '/requests'
      preLoaderRoute: typeof DashboardRequestsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/presence': {
      id: '/_dashboard/presence'
      path: '/presence'
      fullPath: '/presence'
      preLoaderRoute: typeof DashboardPresenceRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/employees': {
      id: '/_dashboard/employees'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof DashboardEmployeesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/alerts': {
      id: '/_dashboard/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof DashboardAlertsRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardAlertsRoute: typeof DashboardAlertsRoute
  DashboardEmployeesRoute: typeof DashboardEmployeesRoute
  DashboardPresenceRoute: typeof DashboardPresenceRoute
  DashboardRequestsRoute: typeof DashboardRequestsRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAlertsRoute: DashboardAlertsRoute,
  DashboardEmployeesRoute: DashboardEmployeesRoute,
  DashboardPresenceRoute: DashboardPresenceRoute,
  DashboardRequestsRoute: DashboardRequestsRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  DashboardRoute: DashboardRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
